### ISSUE TITLE
Plugin Manager

### ISSUE THREAD

**Issue by merlinthemagician** [flika-org/flika#50]
Good afternoon,

After updating flika to the newest version I have problems installing plugins via the plugin manager. Instead of showing the Install Button, only "Loading Information" is shown in the upper right of the window. Please find the traceback below.

Attempting to install the plugin by copying into the plugins directory does not work either.

Thanks a lot for your help,
best wishes
Ivo

P.S.: Traceback when clicking on any of the plugins in plugin manager.

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.9/site-packages/flika-0.2.33-py3.9.egg/flika/app/plugin_manager.py", line 249, in loadThread
    plug.update_info()
  File "/usr/local/lib/python3.9/site-packages/flika-0.2.33-py3.9.egg/flika/app/plugin_manager.py", line 194, in update_info
    new_info = parse(txt)
  File "/usr/local/lib/python3.9/site-packages/flika-0.2.33-py3.9.egg/flika/app/plugin_manager.py", line 85, in parse
    return step(tree)
  File "/usr/local/lib/python3.9/site-packages/flika-0.2.33-py3.9.egg/flika/app/plugin_manager.py", line 75, in step
    for k in item.getchildren():
Attrib

**Comment by merlinthemagician** [comment]
This issue (as well as #51) are caused by calling deprecated methods, in this case getchildren().

**Comment by kyleellefsen** [comment]
The deprecated `getchildren()` method has been removed in flika version 0.2.34. Closing this issue.
