### ISSUE TITLE
Error when starting FLIKA - Assertion Error

### ISSUE THREAD

**Issue by HollyASmith488** [flika-org/flika#53]
Hi Kyle,

I'm guessing it is a while since you have been working on FLIKA, so I hope you're still able to get this message. I have been using FLIKA for a while but just recently I got this error on Anaconda prompt which I have never seen before. I've tried uninstalling and reinstalling both flika and anaconda but I still get the same problem. I have no idea where else to go with this as I am not in any way proficient with code, I have just been using FLIKA in the same way in the lab since the start of my PhD!! It would be great if you could take a look.
Many thanks,
Holly

Starting flika
2022-12-05 20:25:55,140 - ERROR - Uncaught exception
Traceback (most recent call last):
  File "C:\Users\has54.PHARM\Anaconda3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\has54.PHARM\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\has54.PHARM\Anaconda3\Scripts\flika.exe\__main__.py", line 7, in <module>
    sys.exit(exec_())
  File "C:\Users\has54.PHARM\Anaconda3\lib\site-packages\flika\flika.py", line 123, in exec_
    fa = start_flika(sys.argv[1:])
  File "C:\Users\has54.PHARM\Anaconda3\lib\site-packages\flika\flika.py", line 115, in start_flika
    fa = FlikaApplication()
  File "C:\Users\has54.PHARM\Anaconda3\lib\site-packages\flika\app\application.py", line 153, in __init__
    from ..process.file_ import open_file, open_file_from_gui, open_image_sequence_from_gui, open_points, save_file, save_movie_gui, save_points, save_rois
  File "C:\Users\has54.PHARM\Anaconda3\lib\site-packages\flika\process\__init__.py", line 7, in <module>
    from .filters import *
  File "C:\Users\has54.PHARM\Anaconda3\lib\site-packages\flika\process\filters.py", line 89, in <module>
    gaussian_blur = Gaussian_blur()
  File "C:\Users\has54.PHARM\Anaconda3\lib\site-packages\flika\process\filters.py", line 32, in __init__
    assert 'gaussian' in skimage.filters.__dict__  # Make sure your version of skimage is >= 0.12.3
AssertionError

**Comment by HollyASmith488** [comment]
I think I solved this by installing a different version of sci-kit image...

`pip install scikit-image==0.18.0
`
Seemed ok after that

**Comment by HollyASmith488** [comment]
Now I get this error when I try to open Script Editor

`2022-12-05` 22:36:48,467 - ERROR - Uncaught exception
Traceback (most recent call last):
  File "C:\Users\has54.PHARM\Anaconda3\lib\site-packages\flika\app\application.py", line 301, in <lambda>
    return lambda : ScriptEditor.importScript(script)
  File "C:\Users\has54.PHARM\Anaconda3\lib\site-packages\flika\app\script_editor.py", line 214, in importScript
    ScriptEditor.show()
  File "C:\Users\has54.PHARM\Anaconda3\lib\site-packages\flika\app\script_editor.py", line 282, in show
    ScriptEditor.gui = ScriptEditor()
  File "C:\Users\has54.PHARM\Anaconda3\lib\site-packages\flika\app\script_editor.py", line 86, in __init__
    from .terminal import ipython_terminal
  File "C:\Users\has54.PHARM\Anaconda3\lib\site-packages\flika\app\terminal.py", line 23, in <module>
    from ipykernel import find_connection_file
ImportError: cannot import name 'find_connection_file' from 'ipykernel' (C:\Users\has54.PHARM\Anaconda3\lib\site-packages\ipykernel\__init__.py)`

**Comment by gddickinson** [comment]
Hi Holly,

I think Kyle forwarded your email to me... or maybe I'm just on the
subscribed list. Anyway, I've been using Flika a lot recently and I
think your issues are likely due to incompatibility between newer
libraries/python versions and older Flika code. I had a similar issue with
sci-kit and fixed it the same way - by downgrading to 0.18. Could your new
error be due to the version of Python you have installed? What version of
Python are you using to run Flika? A possible quick-fix could be to create
a new conda environment with python 3.7 and use pip to install flika
(specifying scikit=0.18) in the new environment.

best,
George

**Comment by HollyASmith488** [comment]
Hi George,

Thanks so much for your message! Yes I think the newer version of Python (3.9) was definitely the problem. I managed to make a virtual environment running Python 3.6.6 and used pip to install FLIKA with scikit image 0.17.2. That seems to be working now. Thanks again for your help!

Best wishes,
Holly

**Comment by gddickinson** [comment]
Hi Holly,Happy to hear that you were able to fix the problem! Best of luck with your research.George On Dec 6, 2022, at 3:58 AM, HollyASmith488 ***@***.***> wrote:﻿
Hi George,
Thanks so much for your message! Yes I think the newer version of Python (3.9) was definitely the problem. I managed to make a virtual environment running Python 3.6.6 and used pip to install FLIKA with scikit image 0.17.2. That seems to be working now. Thanks again for your help!
Best wishes,
Holly
