### ISSUE TITLE
Unable to install plugins in clean install

### ISSUE THREAD

**Issue by kyleellefsen** [flika-org/flika#60]
I created a fresh flika install in a new python venv using Python 3.11.7 and
flika version 0.3.0 installed from pypi. Once installed, I opened flika by running flika from the command line. I then opened the Plugin Manager and clicked on any of the displayed plugins.

Full stack trace:
```python
2024-02-06 16:41:17,211 - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/Users/kylenv/Desktop/flika_test/flika_py/lib/python3.11/site-packages/flika/app/plugin_manager.py", line 282, in <lambda>
    self.pluginList.currentItemChanged.connect(lambda new, old: self.pluginSelected(new))
                                                                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kylenv/Desktop/flika_test/flika_py/lib/python3.11/site-packages/flika/app/plugin_manager.py", line 348, in pluginSelected
    version = parse_version(plugin.version)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kylenv/Desktop/flika_test/flika_py/lib/python3.11/site-packages/pkg_resources/_vendor/packaging/version.py", line 198, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pkg_resources.extern.packaging.version.InvalidVersion: Invalid version: ''
```

This bug was first reported in a plugin package here: https://github.com/kyleellefsen/detect_puffs/issues/1

**Comment by kyleellefsen** [comment]
This was fixed in https://github.com/flika-org/flika/commit/0e863faa9d3f79aa0a27f9522fe4a7309c97d526

**Comment by gddickinson** [comment]
Thanks for fixing this Kyle!

**Comment by kousikkun** [comment]
Hey! Thanks! it works fine now :)
